---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgvolume
spec:
  accessModes:
   - ReadWriteMany
  mountOptions:
   - hard
   - nfsvers=4.0
   - timeo=60
   - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.6
    path: "/shares/share-e4b9bc5f-5cb0-46ec-9e73-703b345eab0f"
  persistentVolumeReclaimPolicy: "Recycle"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvolume
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "pgvolume"
  storageClassName: ""
